version: '3'
services:
    db:
        image: mongo
        ports:
            - "27017:27017"

    api:
        build: ./api
        ports: 
            - "8080:8080"
        volumes:
            - "./api:/app"
        depends_on: 
            - db