version: '3'
services:
    db:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - db-data:/data/db

    api:
        build: ./api
        ports: 
            - "8080:8080"
        volumes:
            - text-data:/usr/src/app/data
        depends_on: 
            - db

    client:
        build: ./client
        ports:
            - "3000:3000"
        depends_on:
            - api
        stdin_open: true
volumes:
    text-data:
    db-data:
