version: '3'
services:
    db:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - data-volume:/data/db

    api:
        build: ./api
        ports: 
            - "8080:8080"
        volumes:
            - "./api:/app"
        depends_on: 
            - db

volumes:
    data-volume: